// DO NOT EDIT THIS FILE
import React from 'react'
import { BrowserRouter as Router, Route } from 'react-router-dom'

import PageOne from './components/PageOne'
import PageTwo from './components/PageTwo'
import PageThree from './components/PageThree'
import Blank from './components/Blank'

import './App.css'
import './Grid.css'

function App() {
  return (
    <div className="App">
      <Router>
        <Route exact path='/' component={ PageOne } />
        <Route exact path='/2' component={ PageTwo } />
        <Route exact path='/3' component={ PageThree } />
        <Route exact path='/4' component={ Blank } />
      </Router>
    </div>
  )
}

export default App
