// This file is here to make NW.js create the window for the application
// DO NOT edit this file
const startUrl = process.env.NWJS_START_URL || '../build/index.html'

nw.Window.open(startUrl, {}, function(win) {})